# -*- coding: utf-8 -*-
"""mlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQnPzqh8_lYJeVSchYeICmqRVqaws03A
"""

!pip install scikit-learn

import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# 1. Generate a dummy classification dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# 2. Split into training and testing sets
# Corrected 'test_test_split' to 'test_size'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. MLPs are sensitive to feature scaling; scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 4. Define the MLP Architecture
mlp = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    solver='adam',
    max_iter=300,
    random_state=42
)

# 5. Train the model
mlp.fit(X_train, y_train)

# 6. Evaluate accuracy
predictions = mlp.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print(f"Scikit-Learn MLP Accuracy: {accuracy * 100:.2f}%")

# 6. Evaluate accuracy
predictions = mlp.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print(f"Scikit-Learn MLP Accuracy: {accuracy * 100:.2f}%")